version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_TYPE=sqlite
      - DATABASE_NAME=airports.db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_PORT=3000
      - AIRPORTS_DATA_URL=https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat
      - VALID_API_KEYS=dev-api-key-1,dev-api-key-2
    depends_on:
      - redis
    volumes:
      - ./data:/app/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: 